version: '3'
services:
    cloudsql-proxy:
      container_name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.16
      command: /cloud_sql_proxy -dir=/cloudsql -instances=rasa-288821:us-central1:rasa-database=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json
      ports:
        - 5432:5432
      volumes:
        - /home/saiakshitht/rasa-288821-3fcbe572f2e2.json:/secrets/cloudsql/credentials.json
    nginx:
      container_name: "nginx"
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - chatbot_ui
        - rasa
        - action_server
        - cloudsql-proxy
      environment:
        DB_PWD: $DB_PWD
        DB_USER: $DB_USER
        SESSION_SECRET: $SESSION_SECRET
    chatbot_ui:
      container_name: "chatbot_ui"
      build: 
        context: frontend
      ports: 
        - "3000:3000"
      depends_on:
        - cloudsql-proxy
      environment:
        DB_PWD: $DB_PWD
        DB_USER: $DB_USER
        SESSION_SECRET: $SESSION_SECRET
    rasa:
      container_name: "rasa_server"
      build: 
        context: backend
      ports: 
        - "5005:5005"
      depends_on:
        - cloudsql-proxy
      environment:
        DB_PWD: $DB_PWD
        DB_USER: $DB_USER
        SESSION_SECRET: $SESSION_SECRET
    action_server:
      container_name: "action_server"
      image: rasa/rasa-sdk:latest
      build: 
        context: actions
      volumes:
        - ./actions:/app/actions
      depends_on:
        - rasa
        - chatbot_ui
        - cloudsql-proxy
      environment:
        DB_PWD: $DB_PWD
        DB_USER: $DB_USER
        SESSION_SECRET: $SESSION_SECRET
      ports:
        - "5055:5055"
